# Generated by Django 5.2 on 2025-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentbackend', '0002_alter_studentform_address_alter_studentform_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
